import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Rapsy - Account and Data Deletion Policy',
  description: 'Instructions on how to request account and data deletion for the Rapsy application.',
};

export default function RapsyDataDeletionPolicy() {
  return (
    <main className="min-h-screen bg-background text-foreground py-20 px-4 md:px-8 max-w-4xl mx-auto font-sans">
      <div className="mb-10">
        <Link href="/" className="text-primary hover:underline mb-8 inline-block">
          &larr; Back to Portfolio
        </Link>
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-4">Rapsy - Account & Data Deletion</h1>
        <p className="text-muted-foreground text-lg">
          Developer: <strong>Adarsh Kumar Verma</strong>
        </p>
      </div>

      <div className="space-y-12 leading-relaxed">
        <section>
          <h2 className="text-2xl font-semibold mb-4 border-b pb-2">Overview</h2>
          <p className="text-muted-foreground">
            This page provides instructions for users of the <strong>Rapsy</strong> mobile application on how to request the deletion of their accounts and associated data.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 border-b pb-2">In-App Account Deletion (Recommended)</h2>
          <p className="text-muted-foreground mb-4">
            You can immediately delete your account and all associated data directly from within the Rapsy app:
          </p>
          <ol className="list-decimal list-inside space-y-2 text-muted-foreground ml-4">
            <li>Open the <strong>Rapsy</strong> application on your device.</li>
            <li>Go to the <strong>Profile / Settings</strong> tab on the bottom navigation bar.</li>
            <li>Tap on the gear icon (<span className="font-mono p-1 bg-muted rounded text-sm">Settings</span>).</li>
            <li>Under the Account section, tap on <strong>Delete Account</strong>.</li>
            <li>Confirm your action in the dialog prompt.</li>
          </ol>
          <p className="mt-4 text-sm text-amber-600 dark:text-amber-400">
            Note: If you are using Google Sign-In, you may be prompted to re-authenticate (sign out and sign back in) before the deletion can be finalized for security purposes.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 border-b pb-2">Web Deletion Request</h2>
          <p className="text-muted-foreground mb-4">
            If you no longer have access to the app, you can request the deletion of your account and/or specific data (such as workout history) by contacting the developer.
          </p>
          <div className="bg-muted/50 p-6 rounded-lg border border-border">
            <h3 className="text-lg font-medium mb-2">How to request data deletion via email:</h3>
            <ol className="list-decimal list-inside space-y-2 text-muted-foreground">
              <li>Send an email to <strong>avwithai.port@gmail.com</strong> (or your support email address) with the subject line &quot;<strong>Rapsy Data Deletion Request</strong>&quot;.</li>
              <li>Include the email address associated with your Google Sign-In account used in the app.</li>
              <li>Specify whether you want to delete your <strong>Entire Account</strong> or only <strong>Specific Data</strong> (e.g., wipe workout history but keep the account).</li>
            </ol>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 border-b pb-2">Data Processed and Retention Period</h2>
          <div className="space-y-4 text-muted-foreground">
            <p>
              When you delete your account (either via the app or via email request), the following data types are permanently deleted from our Firebase servers within <strong>7 to 14 days</strong>:
            </p>
            <ul className="list-disc list-inside ml-4 space-y-1">
              <li>Your Firebase Authentication profile (Email, Display Name, Profile Photo URL).</li>
              <li>Your usage and workout history data.</li>
            </ul>
            <h3 className="text-lg font-medium text-foreground mt-6 mb-2">Data kept for legal/compliance reasons:</h3>
            <p>
              If you have purchased a Premium or Basic subscription, transaction records generated by Google Play / RevenueCat may be retained by those platforms in accordance with their respective financial and legal compliance policies. We do not store personal credit card information on our servers.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 border-b pb-2">Contact Information</h2>
          <p className="text-muted-foreground">
            Developer: <strong>Adarsh Kumar Verma</strong><br />
            Email: <a href="mailto:avwithai.port@gmail.com" className="text-primary hover:underline">avwithai.port@gmail.com</a>
          </p>
        </section>
      </div>
    </main>
  );
}
